import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://trello.com/');
  await page.getByTestId('bignav').getByRole('link', { name: 'Log in' }).click();
  await page.getByTestId('username').click();
  await page.getByTestId('username').fill('evannji99@gmail.com');
  await page.getByTestId('login-submit-idf-testid').click();
  await page.getByTestId('password').fill('#pwd#');
  await page.getByTestId('password').press('CapsLock');
  await page.getByTestId('password').fill('#pwd#T');
  await page.getByTestId('password').press('CapsLock');
  await page.getByTestId('password').fill('#pwd#T13-1688t#');
  await page.getByTestId('login-submit-idf-testid').click();
  await page.goto('https://trello.com/u/evansgithinji1/boards');
  await page.getByRole('link', { name: 'Test Board afb895cd-aaac-4e5c' }).first().click();
  await page.getByTestId('list-composer-button').click();
  await page.getByRole('textbox', { name: 'Enter list name…' }).fill('N');
  await page.getByRole('textbox', { name: 'Enter list name…' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter list name…' }).fill('New ');
  await page.getByRole('textbox', { name: 'Enter list name…' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter list name…' }).fill('New L');
  await page.getByRole('textbox', { name: 'Enter list name…' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter list name…' }).fill('New List');
  await page.getByTestId('list-composer-add-list-button').click();
  await page.getByRole('button', { name: 'Add a card in New List' }).click();
  await page.getByTestId('list-card-composer-textarea').press('CapsLock');
  await page.getByTestId('list-card-composer-textarea').fill('A');
  await page.getByTestId('list-card-composer-textarea').press('CapsLock');
  await page.getByTestId('list-card-composer-textarea').fill('A card in the new list');
  await page.getByTestId('list-card-composer-add-card-button').click();
});